=== JuliiaRak/LabaDatabases/src/main/resources/xsd/certification.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="SkillType">
        <xs:all>
            <xs:element name="id" type="xs:long"/>
            <xs:element name="skillName" type="xs:string"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="SkillsType">
        <xs:sequence>
            <xs:element name="skill" type="SkillType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="DepartmentType">
        <xs:all>
            <xs:element name="id" type="xs:long"/>
            <xs:element name="departmentName" type="xs:string"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="EmployeeType">
        <xs:all>
            <xs:element name="id" type="xs:long"/>
            <xs:element name="department" type="DepartmentType"/>
            <xs:element name="firstName" type="xs:string"/>
            <xs:element name="lastName" type="xs:string"/>
            <xs:element name="position" type="xs:string"/>
            <xs:element name="salary" type="xs:decimal"/>
            <xs:element name="skills" type="SkillsType"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="CertificationType">
        <xs:sequence>
            <xs:element name="id" type="xs:long"/>
            <xs:element name="employee" type="EmployeeType"/>
            <xs:element name="certificationName" type="xs:string"/>
            <xs:element name="date" type="xs:date"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="certification" type="CertificationType"/>

</xs:schema>

=== JuliiaRak/LabaDatabases/src/main/resources/xml/certification.xml
<?xml version="1.0" encoding="UTF-8"?>
<certification xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="../xsd/certification.xsd">
    <id>1</id>
    <employee>
        <id>1</id>
        <department>
            <id>1</id>
            <departmentName>IT Department 1</departmentName>
        </department>
        <firstName>John</firstName>
        <lastName>Doe</lastName>
        <position>Java Developer</position>
        <salary>50000.00</salary>
        <skills>
            <skill>
                <id>1</id>
                <skillName>Java</skillName>
            </skill>
            <skill>
                <id>2</id>
                <skillName>Automation Testing</skillName>
            </skill>
        </skills>
    </employee>
    <certificationName>Java Certification</certificationName>
    <date>2023-01-01</date>
</certification>
