=== JuliiaRak/LabaDatabases/src/main/resources/xsd/projectEmployee.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="ServiceType">
        <xs:all>
            <xs:element name="id" type="xs:long"/>
            <xs:element name="serviceName" type="xs:string"/>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="cost" type="xs:decimal"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="ServicesType">
        <xs:sequence>
            <xs:element name="service" type="ServiceType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ClientType">
        <xs:all>
            <xs:element name="id" type="xs:long"/>
            <xs:element name="clientName" type="xs:string"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="ProjectType">
        <xs:sequence>
            <xs:element name="id" type="xs:long"/>
            <xs:element name="projectName" type="xs:string"/>
            <xs:element name="client" type="ClientType"/>
            <xs:element name="services" type="ServicesType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="SkillType">
        <xs:all>
            <xs:element name="id" type="xs:long"/>
            <xs:element name="skillName" type="xs:string"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="SkillsType">
        <xs:sequence>
            <xs:element name="skill" type="SkillType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="DepartmentType">
        <xs:all>
            <xs:element name="id" type="xs:long"/>
            <xs:element name="departmentName" type="xs:string"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="EmployeeType">
        <xs:all>
            <xs:element name="id" type="xs:long"/>
            <xs:element name="department" type="DepartmentType"/>
            <xs:element name="firstName" type="xs:string"/>
            <xs:element name="lastName" type="xs:string"/>
            <xs:element name="position" type="xs:string"/>
            <xs:element name="salary" type="xs:decimal"/>
            <xs:element name="skills" type="SkillsType"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="ProjectEmployeeType">
        <xs:all>
            <xs:element name="project" type="ProjectType"/>
            <xs:element name="employee" type="EmployeeType"/>
            <xs:element name="role" type="xs:string"/>
        </xs:all>
    </xs:complexType>

    <xs:element name="projectEmployee" type="ProjectEmployeeType"/>

</xs:schema>

=== JuliiaRak/LabaDatabases/src/main/resources/xml/projectEmployee.xml
<?xml version="1.0" encoding="UTF-8"?>
<projectEmployee xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:noNamespaceSchemaLocation="../xsd/projectEmployee.xsd">
    <project>
        <id>1</id>
        <projectName>XML Project 1</projectName>
        <client>
            <id>1</id>
            <clientName>ABC Company</clientName>
        </client>
        <services>
            <service>
                <id>1</id>
                <serviceName>Service 1</serviceName>
                <description>Service 1 Description</description>
                <cost>100.00</cost>
            </service>
            <service>
                <id>2</id>
                <serviceName>Service 2</serviceName>
                <description>Service 2 Description</description>
                <cost>200.00</cost>
            </service>
        </services>
    </project>
    <employee>
        <id>1</id>
        <department>
            <id>1</id>
            <departmentName>IT Department 1</departmentName>
        </department>
        <firstName>John</firstName>
        <lastName>Doe</lastName>
        <position>Java Developer</position>
        <salary>50000.00</salary>
        <skills>
            <skill>
                <id>1</id>
                <skillName>Java</skillName>
            </skill>
            <skill>
                <id>2</id>
                <skillName>Automation Testing</skillName>
            </skill>
        </skills>
    </employee>
    <role>Developer</role>
</projectEmployee>
